version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mi-mongo-container
    volumes:
      - C:\Users\luis.carretero_bluet\Desktop\procts\gestor-archivos\gestor-archivos\mongo-data:/data/db
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    container_name: mi-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - C:\Users\luis.carretero_bluet\Desktop\procts\gestor-archivos\gestor-archivos\mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mi-mongo-data:
  mi-mysql-data:

  